version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7890:7890"
    volumes:
      - ./water_balance/nginx.conf:/etc/nginx/nginx.conf
      - ./water_balance:/usr/share/nginx/html
    command: ["nginx", "-g", "daemon off;"]
    container_name: nginx_container # Change this to a desired container name

# Add other services below this line as needed
